### ISSUE TITLE
Runs fine w/ Boot = FALSE, error when BOOT = TRUE

### ISSUE THREAD

**Issue by eveistswp** [statdivlab/corncob#123]
Hi Bryan,

I wondered if you might be able to shed light on why I can run this:
dv_analysis <- differentialTest(formula = ~ Sp_Biome, phi.formula = ~ Sp_Biome, formula_null = ~ Sp_Biome, phi.formula_null = ~ 1, data = aridseq, test = "LRT", boot = FALSE, fdr_cutoff = 0.05)
But not:
dv_analysis <- differentialTest(formula = ~ Sp_Biome, phi.formula = ~ Sp_Biome, formula_null = ~ Sp_Biome, phi.formula_null = ~ 1, data = aridseq, test = "LRT", boot = TRUE, fdr_cutoff = 0.05)
Without incurring error:
Error in if (is.nan(val) || any(phi <= sqrt(.Machine$double.eps)) || any(phi >=  : 
  missing value where TRUE/FALSE needed

Thanks!

**Comment by bryandmartin** [comment]
Someone else had a similar issue and I'm wondering if it's the same problem (#121).

Can you first try manually (re-)installing the "trust" and "optimr" packages? I'm wondering if they aren't loading properly for some reason as was the case there. If that doesn't work the solution might take a bit more information to suss out. 

One other thing to try, just to see if this is the issue, do you still have this error with `boot = TRUE` if you provide arguments for `inits`?

**Comment by eveistswp** [comment]
Hi Bryan,

I tried re-installing the packages above and this seemed to improve performance in some but not all cases. It seems to me I have this error most often when the test in question returns nothing significant (if that helps).

As I'm not overly familiar with models, I haven't tried editing 'inits' - what is the idea here?

Thanks,
Evie

**Comment by bryandmartin** [comment]
@eveistswp ”inits” are the initial parameter values for optimization. Sometimes, when I see that the optimization failed, as I see here, an easy potential work around is to manually set initialization points. How many bootstrap iterations are you doing (“B”)?

**Comment by adw96** [comment]
Hi @eveistswp -- we haven't heard from you in a while on this, so please reopen this issue if need more assistance.
