### ISSUE TITLE
Model does not converge 

### ISSUE THREAD

**Issue by kmdesorcy** [statdivlab/corncob#135]
Hello, 

I'm trying to use corncob to test the differential abundance of all taxa in my samples across a categorical variable with 2 levels. I have ~70 samples.  I'm getting an error message that the model is failing to converge.  The error message states that the model is overspecified but I'm not sure I understand if I have only 1 categorical variable with 2 levels and a high # of samples. Any help would be very much appreciated. 

cctest <- differentialTest(formula = ~ rn,
                                phi.formula = ~ rn,
                                formula_null = ~ 1,
                                phi.formula_null = ~ rn,
                                test = "Wald", boot = FALSE,
                                data = gut.r.week1,
                                fdr_cutoff = 0.05)

Error in differentialTest(formula = ~rn, phi.formula = ~rn,  : 
  All models failed to converge! 

           If you are seeing this, it is likely that your model is overspecified. This occurs when your sample size is not large enough to estimate all the parameters of your model. This is most commonly due to categorical variables that include many categories. 

           Alternatively, double-check your values for the arguments `link`, `phi.link`, and `method` to makes sure that they follow the specified options. 

           To confirm you have fixed the issue, try running a model for a single taxon with bbdml.

**Comment by adw96** [comment]
Hi @kmdesorcy -- can you show us the output of `model.matrix(~rn, data = gut.r.week1)`? That should be able to tell us how the mean and dispersion models are being specified and if overparametrization is your problem.

**Comment by kmdesorcy** [comment]
Thank you for your reply!

> model.matrix(~rn, data = gut.r.week1)
    (Intercept) raceNewNA
1             1         1
2             1         1
3             1         0
4             1         0
5             1         0
6             1         0
7             1         0
8             1         0
9             1         0
10            1         0
11            1         1
12            1         1
13            1         0
14            1         0
15            1         0
16            1         0
17            1         1
18            1         1
19            1         1
20            1         1
21            1         1
22            1         1
23            1         1
24            1         1
25            1         1
26            1         1
27            1         1
28            1         1
29            1         1
30            1         1
31            1         1
32            1         1
33            1         1
34            1         1
35            1         1
36            1         1
37            1         1
38            1         1
39            1         1
40            1         1
41            1         1
42            1         1
43            1         0
44            1         0
45            1         0
46            1         0
47            1         1
48            1         1
49            1         1
50            1         1
51            1         1
52            1         1
53            1         1
54            1         1
55            1         1
56            1         1
57            1         1
58            1         0
59            1         0
60            1         0
61            1         0
62            1         0
63            1         0
64            1         0
65            1         0
66            1         1
67            1         1
68            1         1
69            1         1
70            1         1
71            1         1
72            1         1
73            1         1
74            1         1
75            1         0
76            1         0
77            1         0
78            1         0
79            1         0
80            1         0
81            1         0
82            1         0
83            1         0
84            1         0
85            1         1
86            1         1
87            1         1
88            1         0
89            1         0
90            1         0
91            1         0
92            1         0
93            1         0
94            1         0
95            1         0
96            1         0
97            1         0
98            1         0
99            1         0
100           1         0
101           1         0
102           1         0
103           1         0
104           1         1
105           1         1
106           1         0
107           1         0
108           1         0
109           1         0
110           1         1
111           1         1
112           1         1
113           1         1
114           1         1
115           1         1
116           1         1
117           1         1
118           1         1
119           1         1
120           1         1
121           1         1
122           1         1
123           1         1
124           1         1
125           1         1
126           1         0
127           1         0
128           1         0
129           1         1
130           1         1
131           1         1
132           1         1
133           1         0
134           1         0
135           1         0
136           1         0
137           1         1
138           1         1
139           1         1
140           1         1
141           1         1
142           1         1
143           1         0
144           1         0
145           1         1
146           1         1
147           1         1
148           1         1
149           1         1
150           1         1
151           1         0
152           1         0
153           1         0
154           1         0
155           1         0
156           1         0
157           1         0
158           1         1
159           1         0
160           1         0
161           1         0
162           1         1
163           1         1
164           1         1
165           1         1
166           1         1
167           1         1
168           1         1
169           1         1
170           1         1
171           1         1
172           1         1
173           1         1
174           1         1
175           1         1
176           1         1
177           1         1
178           1         1
179           1         1
180           1         1
181           1         1
182           1         1
183           1         0
184           1         0
185           1         1
186           1         1
187           1         1
188           1         1
189           1         1
190           1         1
191           1         1
192           1         1
193           1         1
194           1         0
195           1         0
196           1         0
197           1         1
attr(,"assign")
[1] 0 1
attr(,"contrasts")
attr(,"contrasts")$rn
[1] "contr.treatment"

**Comment by adw96** [comment]
Closing bc no follow-up received
