### ISSUE TITLE
plot options

### ISSUE THREAD

**Issue by jorondo1** [statdivlab/corncob#144]
Hi!
I've been playing around with corncob and I can't figure out how to properly format the plots. The plot() function somehow stitches together all taxonomic levels from the taxonomy. Can we prevent it from doing that?
![Rplot](https://user-images.githubusercontent.com/97983060/194558204-840ca71a-7a7a-425a-b8af-0406d3380600.png)
My ps object is not formatted this way (row.names are species only) so I don't understand that it would stitch all the info from the tax_table columns like that since I already have unique row identifiers.

Also, is there a way to feed the differentialTest output in ggplot to make them more flexible? I'm far from being an R expert so the answer to this might be obvious, but if you have examples to point me to I'd be very thankful.

Cheers !

**Comment by jorondo1** [comment]
Hi again. After searching through the source codes I realised there was more than just the plot() function. 

I would suggest you specify plot.differentialTest in the vignettes so it's easier to find help, since ?plot doesn't show the help file for these functions.

Cheers,

**Comment by adw96** [comment]
That’s a good point, @jorondo1 ! We should definitely have an example of this in a vignette. 

@gthopkins this should be easy — would you mind updating the vignettes to include an example of how we can do plotting, and how users can get the data that they need out of a summary table to make their own custom plots. This is not urgent, but would be good to have wrapped up within the next 2-3 weeks.

**Comment by gthopkins** [comment]
@adw96 yes, I will update the `corncob` vignette accordingly. Thank you for describing the timeline on this!

**Comment by svteichman** [comment]
Closing this issue because it is addressed in PR #180
