### ISSUE TITLE
Output models despite unable to converge

### ISSUE THREAD

**Issue by jorondo1** [statdivlab/corncob#145]
Hi,
Is there a way to save a differentialTest output even if no models converge? We'd be interested to report the absence of significant taxa in the effects we are looking at, and having some numbers to support that.

Cheers!

**Comment by svteichman** [comment]
Hi @jorondo1, 

What kind of output are you interested in? What numbers to support the absence of significant taxa would be helpful? 

Best,
Sarah

**Comment by adw96** [comment]
@svteichman Since normally "no models converged" indicate a coding issue, didn't we update corncob so that it prints out the error message for the first failed model?

If so, I think it's okay to close this issue -- given inactivity AND that we have more helpful error messages now.

**Comment by svteichman** [comment]
Yes, since this issue was posted we've updated `corncob` to give error messages to help figure out why no models successfully converged. I suspect that it is fairly uncommon for all models to fail to converge for a call to corncob without coding errors.
