### ISSUE TITLE
rename master -> main

### ISSUE THREAD

**Issue by adw96** [statdivlab/corncob#152]
Can we please change the name of the branch from master to main? I believe this is easy to do and better reflects the StatDivLab's goal to be an antiracist organization. 

If we see any master branches on other SDL repos, let's also action renaming them.

**Comment by svteichman** [comment]
SDL repos that were created in 2021 and later have their default branch named main and repos created in 2020 or previously have their default branch named master (this includes `q2-breakaway`, `CatchMore`, `q2-corncob`, `mbqc`). The exceptions to this timing convention are `DivNet` and `breakaway` which have had their default branches updated from master to main at some point in the last few years.
