### ISSUE TITLE
Option for non-count estimator (estimating equations interpretation)

### ISSUE THREAD

**Issue by adw96** [statdivlab/corncob#153]
Currently, corncob is set up to only take integer $W_ij$'s, which makes sense as it outputs MLEs from a beta-binomial model. However, we could consider a generalization for non-integer W_ij's, using the beta-binomial model to motivate estimating equations, which would still give us CANE estimates. Useful for modeling coverages! (and needed for a future project for which corncob is a dependency)

TODO: generalized corncob to estimate under non-integer W_ij's. 

*Must* output a warning, because then people can throw anything in, without any guarantee that what they are doing is sensible, and previously this was often caught by the non-integer error. 

Another option is to have a optional flag that defaults to FALSE `allow_noninteger`... maybe I like this idea better?

**Comment by adw96** [comment]
Implementation of this currently on `testing`  1c3dd4a. Some notes

- I believe that the existing functionality to throw an error with non integer accounts is maintained by default. The error message is "Double-check and correct your data, and/or force the model to fit with `allow_noninteger`"
- If `allow_noninteger` is `TRUE` the model will fit. Checks confirm that rounding non-integers gives similar results.

Still TODO
- Sandwich standard error should be returned by default if `allow_noninteger` is TRUE. Very grateful to @bryandmartin for making this easy (so it seems). 
- Think about whether LRT should be banned given EE setting (is there a model-robust interpretation?)
- `dbetabinom_cts_mod` and relatives uses code from `VGAM::dbetabinom.ab` but relaxes checks. Best practice for crediting the code source? Perhaps @svteichman could do some research and help advise 🙏 

No need to review yet, @svteichman -- I'll open a PR when it's ready.

**Comment by bryandmartin** [comment]
This is a great new feature!

**Comment by svteichman** [comment]
Closing because this is implemented in merged pull request #155
