### ISSUE TITLE
`aes_string()` was deprecated in ggplot2 3.0.0.

### ISSUE THREAD

**Issue by adw96** [statdivlab/corncob#158]
Hi @MariaAVC would love your help dealing with a warning we're now getting in a test. 

`test_s3()` is now throwing a warning: 

`aes_string()` was deprecated in ggplot2 3.0.0.

I couldn't figure this out quickly and would love your help transitioning this call to an `aes()` call. 

I believe that this warning is only thrown once, then is silenced, so to reproduce it I've been just closing my R project and reopening before testing. 

Lmk if you have any questions! 🙏

**Comment by MariaAVC** [comment]
Hello @adw96. I am a bit confused. I was not able to reproduce the problem. When I run test_s3.R both using corncob downloaded directly from GitHub, as well as from my local copy, all tests pass with flying colors. Are you sure the message is coming from that test? 

Best,
María

**Comment by adw96** [comment]
Yes -- here's the message I get when I `test()`. I also can't reproduce it directly from `test_s3`, but for whatever reason the "global" testing environment triggers it, at least the first time I run it.  

<img width="1139" alt="Screenshot 2023-11-06 at 9 55 42 AM" src="https://github.com/statdivlab/corncob/assets/17593682/8e910f5d-f8d1-4745-8757-0046c4a89af3">

**Comment by adw96** [comment]
Lmk if you can't reproduce it this way. While I know it's hard to update code that doesn't give warnings locally, if you're able to investigate how to replace `aes_string()` with `aes()`, that would be wonderful 🙏

**Comment by MariaAVC** [comment]
I was able to reproduce the warning in test() and I have changed the respective code, so now that warning should be gone. The pull request for this change has been made on branch AESchange
