### ISSUE TITLE
`contrastsTest` returns NULL for all return values

### ISSUE THREAD

**Issue by svteichman** [statdivlab/corncob#160]
I believe there is a problem with the use of the function `limma::makeContrasts()` called by the helper function `waldchisq_test()` when running `contrastsTest()`. There are two issues that I see:

- `limma` has been removed from cran, and there is no error or warning when the package is not installed and the function is called, instead the function silently returns NA
- when `limma` is installed (it is available on Bioconductor), running `limma::makeContrasts()" results in an error about an argument not able to be found, although no error or warning is thrown and the function silently returns NA

I have currently added a warning to the `contrastsTest()` function that behavior is not as expected but I think this should be looked at in more detail.

**Comment by adw96** [comment]
Good catch!

If I recall correctly, `statdivlab/rigr` has a way to test contrasts. If we can turn a limma dependency into a rigr dependency, that would give us more control over failures. 

Also, #$*& CRAN for removing all of these foundational packages!

**Comment by svteichman** [comment]
It turns out the function works for and the examples/tests for this function weren't working. They've been fixed in PR #165 so  I'm closing this issue.
