### ISSUE TITLE
github.io site

### ISSUE THREAD

**Issue by adw96** [statdivlab/corncob#161]
It would be great to have the documentation available online without rendering vignettes, etc. 

Personally I think github.io sites are pretty cool for this -- eg https://statdivlab.github.io/rigr/

 In my wildest dreams we can use GitHub actions to update and render the website every time a commit to `main` happens

@bryandmartin -- did you have a reason for not making one? I appreciate your insights and expertise on this as we weigh up options for regarding reproducibility and accessibility of documentation 🙏

**Comment by bryandmartin** [comment]
No particular reason besides a lack of time and resources invested into the software. I think an io site would be a great way to have pre-rendered documentation.

**Comment by adw96** [comment]
Thank you! That's very helpful! We'll investigate.

**Comment by svteichman** [comment]
Closing because this is all set up now!
