### ISSUE TITLE
Model could not be optimized!

### ISSUE THREAD

**Issue by maherrl** [statdivlab/corncob#181]
Hello, I get the following error when I try to run a model with a single ASV:

`corncob_da <- bbdml(formula = ASV_18S_1 ~ State,
                    phi.formula = ~ State,
                    data = PS)`
`summary(corncob_da)`
`Error in bbdml(formula = ASV_18S_1 ~ State, phi.formula = ~1, data = PS) : 
  Model could not be optimized! Try changing initializations or simplifying your model.`

Do you have recommendations for how to change initializations? I'm not sure what I should specify with inits =.

Here is a link to the PS phyloseq object: [https://www.dropbox.com/scl/fi/6zb85k7c1xmoweogphnws/ps_da_analysis.RDS?rlkey=krjmucsqr62y4rtuq71j9wzvu&st=8x5b85x9&dl=0]

Thanks,

**Comment by adw96** [comment]
Thanks for letting us know, @maherrl ! 

@gthopkins -- would you be able to look into this within the next few days? I'll do my best to help over slack if needed. Thanks so much!!

**Comment by gthopkins** [comment]
Hi @maherrl, you can change initializations as follows:

```
PSdf <- corncob::convert_phylo(PS, "ASV_18S_1")
inits <- matrix(0, ncol = 12)
colnames(inits) <- c(colnames(model.matrix(~ State, data = PSdf)),
                     colnames(model.matrix(~ State, data = PSdf)))
corncob_da <- bbdml(formula = ASV_18S_1 ~ State,
                    phi.formula = ~ State,
                    data = PS,
                    inits = init_0)
```

I checked that the `bbdml()` function will complete with this initialization on your data. The column names correspond to the formula and phi.formula covariate columns, respectively. Please let us know if there are any further issues using `corncob`!
